version: "3.8"
services:
  db:
    image: mongo:latest
    container_name: "goddd-db"
    restart: always
    volumes:
      - db:/data/db
    ports:
        - "27017:27017"
volumes:
    db:
        driver: local
